
# Replace '[YOUR_AWS_RDS_ENDPOINT]' with the real endpoint copied from your AWS RDS console
spring.datasource.url=jdbc:mysql://localhost:3306/ai_ecommerce?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Abhishek12345@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
